# Generated by Django 6.0.2 on 2026-02-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pickuppoint_order_delivery_date_order_pickup_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickupPoint',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт выдачи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код получения'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена в момент заказа'),
        ),
    ]
